account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .forms import (PwdResetConfirmForm, PwdResetForm, UserLoginForm)

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html',
                                                form_class=UserLoginForm), name='login'),
    path('logout/', views.custom_logout, name='logout'),
    path('register/', views.account_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>)/', views.account_activate, name='activate'),
    # Reset password
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="account/password_reset_form.html",
                                                                 success_url='password_reset_email_confirm',
                                                                 email_template_name='account/password_reset_email.html',
                                                                 form_class=PwdResetForm), name='pwdreset'),
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset_confirm.html',
                                                                                                success_url='password_reset_complete/',
                                                                                                form_class=PwdResetConfirmForm),
         name="password_reset_confirm"),
    path('password_reset/password_reset_email_confirm/',
         TemplateView.as_view(template_name="account/reset_status.html"), name='password_reset_done'),
    path('password_reset_confirm/Mg/password_reset_complete/',
         TemplateView.as_view(template_name="account/reset_status.html"), name='password_reset_complete'),
    # User dashboard
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/edit/', views.edit_details, name='edit_details'),
    path('profile/delete_user/', views.delete_user, name='delete_user'),
    path('profile/delete_confirm/', TemplateView.as_view(template_name="account/delete_confirm.html"), name='delete_confirmation'),
]

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('add/', views.add, name='add'),
    path('recent-orders/', views.RecentOrdersView.as_view(), name="recent-orders"),
]

shop/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import permissions




urlpatterns = [

    path('admin/', admin.site.urls),
    path('orders/', include('orders.urls', namespace='orders')),
    path('account/', include('account.urls', namespace='account')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('store.urls', namespace='store')),
    path('api/v1/', include('core.api.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
from decimal import Decimal
from django.conf import settings
from django.db import models

from store.models import Product


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='order_user')
    full_name = models.CharField(max_length=50)
    address1 = models.CharField(max_length=250)
    address2 = models.CharField(max_length=250)
    city = models.CharField(max_length=100)
    phone = models.CharField(max_length=100)
    post_code = models.CharField(max_length=20)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    total_paid = models.DecimalField(max_digits=5, decimal_places=2)
    order_key = models.CharField(max_length=200)
    billing_status = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return str(self.created)


class OrderItem(models.Model):
    order = models.ForeignKey(Order,
                              related_name='items',
                              on_delete=models.CASCADE)
    product = models.ForeignKey(Product,
                                related_name='order_items',
                                on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.id)

orders/forms.py
from django.forms import ModelForm
from .models import Order


class MyForm(ModelForm):
    class Meta:
        model = Order
        fields = ['full_name', 'address1', 'city', 'post_code', 'phone']

orders/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http.response import JsonResponse
from django.shortcuts import render, redirect
import datetime

from django.urls import reverse
from django.views import View

from basket.basket import Basket

from .models import Order, OrderItem


def add(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':

        order_key = request.POST.get('order_key')
        user_id = request.user.id
        baskettotal = basket.get_total_price()

        # Check if order exists
        if Order.objects.filter(order_key=order_key).exists():
            pass
        else:
            order = Order.objects.create(user_id=user_id, full_name='name', address1='add1',
                                address2='add2', total_paid=baskettotal, order_key=order_key)
            order_id = order.pk

            for item in basket:
                OrderItem.objects.create(order_id=order_id, product=item['product'], price=item['price'], quantity=item['qty'])

        response = JsonResponse({'success': 'Return something'})
        return response


def payment_confirmation(data):
    Order.objects.filter(order_key=data).update(billing_status=True)


def user_orders(request):
    user_id = request.user.id
    orders = Order.objects.filter(user_id=user_id).filter(billing_status=True)
    return orders



class RecentOrdersView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        try:
            user_id = request.user.id
            recent_orders = Order.objects.filter(user_id=user_id)[0:10]
        except Order.DoesNotExist:
            return redirect(reverse("account:login"))
        return render(request, "orders/recent_orders.html", {
            'recent_orders': recent_orders,
        })

orders/templates/orders/home.html
{% extends "base.html" %}
{% load static %}
{% block title %}Payment{% endblock %}
{% block content %}

<style>
  .account-form input,
    {
    border: 2px solid #ccc;
    height: calc(2em + .75rem + 2px);
  }

  .form-control {
    border: 2px solid #ccc;
  }

  .account-form input:focus {
    border-color: #1497ff;
    box-shadow: inset 0 0px 0px rgba(0, 0, 0, 0.075), 0 0 0px rgba(255, 0, 0, 0.6);
  }
</style>

<div class="container-fluid">
  <div class="row no-gutter">
    <div class="col-md-12">
      <div class="login d-flex align-items-center py-5">
        <div class="container">
          <div class="row">
            <div id="payment-form" class="col-12 col-lg-6 mx-auto">
              <h3 class="mb-3">Billing address</h3>
              <!-- Error messages in this element -->
              <div id="card-errors" class="a" role="alert"></div>
              <form>
                <div class="row g-3">
                  <div class="col-sm-7">
                    <label for="firstName" class="form-label">Customer Name</label>
                    <input type="text" class="form-control" id="custName" placeholder="" required>
                    <div class="invalid-feedback">
                      Valid first name is required.
                    </div>
                  </div>
                  <div class="col-12">
                    <label for="email" class="form-label">Email <span class="text-muted">(Optional)</span></label>
                    <input type="email" class="form-control" id="email" placeholder="you@example.com">
                    <div class="invalid-feedback">
                      Please enter a valid email address for shipping updates.
                    </div>
                  </div>
                  <div class="col-12">
                    <label for="address" class="form-label">Address</label>
                    <input type="text" class="form-control" id="custAdd" placeholder="1234 Main St" required>
                    <div class="invalid-feedback">
                      Please enter your shipping address.
                    </div>
                  </div>
                  <div class="col-12">
                    <label for="address2" class="form-label">Address 2 <span
                        class="text-muted">(Optional)</span></label>
                    <input type="text" class="form-control" id="custAdd2" placeholder="Apartment or suite">
                  </div>
                  <div class="col-md-5">
                    <label for="country" class="form-label">Country</label>
                    <select class="form-select" id="country" required>
                      <option value="">Choose...</option>
                      <option>United States</option>
                    </select>
                    <div class="invalid-feedback">
                      Please select a valid country.
                    </div>
                  </div>
                  <div class="col-md-4">
                    <label for="state" class="form-label">State</label>
                    <select class="form-select" id="state" required>
                      <option value="">Choose...</option>
                      <option>California</option>
                    </select>
                    <div class="invalid-feedback">
                      Please provide a valid state.
                    </div>
                  </div>
                  <div class="col-md-3">
                    <label for="Postcode" class="form-label">Postcode</label>
                    <input type="text" class="form-control" id="postCode" placeholder="" required>
                    <div class="invalid-feedback">
                      Zip code required.
                    </div>
                  </div>
                </div>
                <hr class="my-4">
                <h4 class="mb-3">Payment</h4>
                <label for="card-element">Credit or debit card</label>
                <div id="card-element" class="form-control form-control-payment">
                  <!-- Payment elements will appear here -->
                </div>
                <hr class="my-4">
                <button id="submit" class="btn btn-primary w-100 fw-bold" data-secret="{{ client_secret }}">Pay</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<script>
    {% comment %} Make csrf token availble in JS files {% endcomment %}
    var CSRF_TOKEN = '{{ csrf_token }}';
</script>
<script src="https://js.stripe.com/v3/"></script>
<script src="{% static 'payment/index.js' %}" data-rel-js></script>

{% endblock %}

orders/templates/orders/recent_orders.html
{% extends "base.html" %} {% load static %}
{% block title %}Basket Summary{%endblock %}
{% block content %}

<main class="pt-5">
  <div class="container" style="max-width: 1000px">
    <div class="col-12">
      <h1 class="h2">Your Dashboard</h1>
    </div>
    <div class="col-12 d-flex justify-content-between">
      <div>Manage your <b>orders</b> and personal details</div>
      <div><a href="{% url "account:edit_details" %}">Change Details</a></div>

    </div>
    <hr />
  </div>
  <div class="container" style="max-width: 1000px">
    {% for order in recent_orders %}
    <div class="row g-3">
      
      <div class="col-12 bg-light p-3 d-flex justify-content-between">
        <div class="d-flex d-flex-inline">

          <div class="dropdown">
          <a class="text-reset text-decoration-none dropdown-toggle" href="#" role="link" id="dropdownLink" data-bs-toggle="dropdown" aria-expanded="false">
          details
          <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" class="bi bi-chevron-down" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/>
          </svg>
          </a>

          <ul class="dropdown-menu" aria-labelledby="dropdownLink">
            <li class="item small">{{order.full_name}}</li>
            <li class="item small">{{order.address1}}</li>
            <li class="item small">{{order.address2}}</li>
            <li class="item small">{{order.post_code}}</li>
          </ul>
          </div>

        </div>
        <div class="text-end">
          price: <span class="fw-bold">${{ order.total_paid }}</span>
        </div>
      </div>
      <div class="col-md-5 col-lg-4 order-md-last p-0 order-3">

      </div>

      <div class="col-md-7 col-lg-8 p-0">

        {% for item in order.items.all %}

        <div class="card mb-3 border-0">
          <div class="row g-0">
            <div class="col-md-2 d-none d-md-block">
              <img class="img-fluid" style="width:90px" src="{{item.product.image.url}}" />
            </div>
            <div class="col-md-10">
              <div class="card-body p-1">
                <a class="text-decoration-none" href="{{ item.product.get_absolute_url }}">
                  <p class="card-text small">{{item.product|title}}</p>
                </a>
              </div>
            </div>
          </div>
        </div>

        
        {% endfor %}


      </div>

    </div>
    {% endfor %}

  </div>
</main>





{% endblock %}